/*
Utilized in RSAGUI
Authors : Dhrumil Patel, Kena Patel
*/

import org.xml.sax.SAXException;

import javax.swing.*;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import java.awt.*;
import java.io.*;


public class EncryptBlockFilePanel extends javax.swing.JPanel {

    private javax.swing.JButton create;

    /**
     * Creates new form KeyCreation
     */
    public EncryptBlockFilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        create = new javax.swing.JButton();


        create.setText("Start");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    createActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Some error occurred during encryption of block file. Please try again.");

                }
            }
        });
        setLayout(new BorderLayout());
        add(create, BorderLayout.CENTER);

    }// </editor-fold>

    private void createActionPerformed(java.awt.event.ActionEvent evt) throws SAXException, TransformerException, ParserConfigurationException, IOException {

        String blocked_filename = JOptionPane.showInputDialog("Enter block file name: ");

        String encrypted_filename = JOptionPane.showInputDialog("Enter encrypted block file name: ");
        String key_file = JOptionPane.showInputDialog("Enter public key file name: ");

        RSA.Key key = RSA.getKey(key_file);
        BufferedReader reader = new BufferedReader(new FileReader(blocked_filename));
        PrintWriter writer = new PrintWriter(new File(encrypted_filename));
        while (true) {
            String line = reader.readLine();
            if (line == null) break;
            writer.println(RSA.encrypt(new LargeInteger(line), key.n, key.d));

        }
        writer.close();
        JOptionPane.showMessageDialog(null, "Successfully encrypted block file!");

    }
}
