/*
Utilized in RSAGUI
Authors : Dhrumil Patel, Kena Patel
*/


import org.xml.sax.SAXException;

import javax.swing.*;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;


public class UnblockFilePanel extends javax.swing.JPanel {

    private javax.swing.JButton create;

    /**
     * Creates new form KeyCreation
     */
    public UnblockFilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        create = new javax.swing.JButton();


        create.setText("Start");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    createActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Some error occurred during unblocking file creation. Please try again.");

                }
            }
        });
        setLayout(new BorderLayout());
        add(create, BorderLayout.CENTER);

    }// </editor-fold>

    private void createActionPerformed(java.awt.event.ActionEvent evt) throws SAXException, TransformerException, ParserConfigurationException, IOException {


        String blocked_filename = JOptionPane.showInputDialog("Enter block file name: ");
        int block = Integer.parseInt(JOptionPane.showInputDialog("Enter block size: "));
        String filename = JOptionPane.showInputDialog("Enter ascii text file name:: ");
        BufferedReader reader = new BufferedReader(new FileReader(blocked_filename));
        ArrayList<LargeInteger> blocked_values = new ArrayList<>();
        while (true) {
            String line = reader.readLine();
            if (line == null) break;
            blocked_values.add(new LargeInteger(line));
        }
        String message = RSA.unblock(blocked_values, block);
        PrintWriter writer = new PrintWriter(new File(filename));
        writer.print(message);
        writer.close();
        JOptionPane.showMessageDialog(null, "Successfully unblocked block file!");


    }
}
